"""goods table

Revision ID: 617555d8d91a
Revises: 84b89f5b2004
Create Date: 2022-08-18 17:17:08.739494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617555d8d91a'
down_revision = '84b89f5b2004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('buy_price', sa.Integer(), nullable=True))
    op.add_column('goods', sa.Column('sell_price', sa.Integer(), nullable=True))
    op.add_column('goods', sa.Column('profit', sa.Integer(), nullable=True))
    op.drop_column('goods', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('price', sa.INTEGER(), nullable=True))
    op.drop_column('goods', 'profit')
    op.drop_column('goods', 'sell_price')
    op.drop_column('goods', 'buy_price')
    # ### end Alembic commands ###
