"""goods table

Revision ID: 518605001046
Revises: 147dd706ca60
Create Date: 2022-04-20 20:55:00.629108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518605001046'
down_revision = '147dd706ca60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=140), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('descripton', sa.String(length=500), nullable=True),
    sa.Column('seller', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seller'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###
