"""goods table

Revision ID: 5aa14d2a6aa4
Revises: b655c7127177
Create Date: 2022-05-23 16:19:07.588630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa14d2a6aa4'
down_revision = 'b655c7127177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'verified')
    # ### end Alembic commands ###
